parameters:
    statistics.handler.class: LoginCidadao\StatsBundle\Handler\StatsHandler

services:
    statistics.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LoginCidadao\StatsBundle\Entity\Statistics

    statistics.handler:
        class: %statistics.handler.class%
        arguments:
            - "@statistics.repository"
        lazy: true

    statistics.subscriber:
        class: 'LoginCidadao\StatsBundle\EventListener\StatisticsSubscriber'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
